In [35]:
import pandas as pd
df = pd.read_csv("salaries-by-college-major.csv")
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [37]:

df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [13]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [14]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [15]:
clean_df = df.dropna()
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [16]:
clean_df["Starting Median Salary"]

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [18]:
clean_df["Starting Median Salary"].max()

74300.0

In [20]:
clean_df["Starting Median Salary"].idxmax()

43

In [21]:
clean_df["Starting Median Salary"][43]

74300.0

In [22]:
clean_df["Undergraduate Major"].loc[43]

'Physician Assistant'

In [23]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [25]:
print(clean_df['Mid-Career Median Salary'].max())
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")
clean_df["Undergraduate Major"]

107000.0
Index for the max mid career salary: 8

0                               Accounting
1                    Aerospace Engineering
2                              Agriculture
3                             Anthropology
4                             Architecture
5                              Art History
6                                  Biology
7                      Business Management
8                     Chemical Engineering
9                                Chemistry
10                       Civil Engineering
11                          Communications
12                    Computer Engineering
13                        Computer Science
14                            Construction
15                        Criminal Justice
16                                   Drama
17                               Economics
18                               Education
19                  Electrical Engineering
20                                 English
21                                    Film
22                                 Finance
23                                Forestry
24                               Geography
25                                 Geology
26                          Graphic Design
27              Health Care Administration
28                                 History
29                   Hospitality & Tourism
30                  Industrial Engineering
31             Information Technology (IT)
32                         Interior Design
33                 International Relations
34                              Journalism
35    Management Information Systems (MIS)
36                               Marketing
37                                    Math
38                  Mechanical Engineering
39                                   Music
40                                 Nursing
41                               Nutrition
42                              Philosophy
43                     Physician Assistant
44                                 Physics
45                       Political Science
46                              Psychology
47                                Religion
48                               Sociology
49                                 Spanish
Name: Undergraduate Major, dtype: object

In [26]:
print(clean_df['Mid-Career Median Salary'].max())

107000.0

In [27]:
clean_df["Undergraduate Major"]

0                               Accounting
1                    Aerospace Engineering
2                              Agriculture
3                             Anthropology
4                             Architecture
5                              Art History
6                                  Biology
7                      Business Management
8                     Chemical Engineering
9                                Chemistry
10                       Civil Engineering
11                          Communications
12                    Computer Engineering
13                        Computer Science
14                            Construction
15                        Criminal Justice
16                                   Drama
17                               Economics
18                               Education
19                  Electrical Engineering
20                                 English
21                                    Film
22                                 Finance
23                                Forestry
24                               Geography
25                                 Geology
26                          Graphic Design
27              Health Care Administration
28                                 History
29                   Hospitality & Tourism
30                  Industrial Engineering
31             Information Technology (IT)
32                         Interior Design
33                 International Relations
34                              Journalism
35    Management Information Systems (MIS)
36                               Marketing
37                                    Math
38                  Mechanical Engineering
39                                   Music
40                                 Nursing
41                               Nutrition
42                              Philosophy
43                     Physician Assistant
44                                 Physics
45                       Political Science
46                              Psychology
47                                Religion
48                               Sociology
49                                 Spanish
Name: Undergraduate Major, dtype: object

In [28]:
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")

Index for the max mid career salary: 8

In [29]:
print(clean_df['Starting Median Salary'].min())

34000.0

In [30]:
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

'Spanish'

In [31]:
print(clean_df['Starting Median Salary'].min())
clean_df['Undergraduate Major'].loc[clean_df['Starting Median Salary'].idxmin()]

34000.0

'Spanish'

In [32]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [33]:
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")

Index for the max mid career salary: 8